base:
  enabled: False
  args:
  - seed
  - strength
  - scale
  - input_image
  - a_prompt
  - prompt
  - image_resolution
  - eta
  - n_prompt
  - num_samples
  - ddim_steps
  - guess_mode
  ckpt_path: ''
  config_path: ''
  detector: ''
  postprocess: ''
  preprocess: ''
canny:
  enabled: True
  args:
  - high_threshold
  - low_threshold
  ckpt_path: ./models/control_sd15_canny.pth
  config_path: ./models/cldm_v15.yaml
  detector: annotator.canny.CannyDetector
  postprocess: postprocess.postprocess_canny
  preprocess: preprocess.preprocess_canny
depth:
  enabled: True
  args:
  - detect_resolution
  ckpt_path: ./models/control_sd15_depth.pth
  config_path: ./models/cldm_v15.yaml
  detector: annotator.midas.MidasDetector
  postprocess: postprocess.postprocess_depth
  preprocess: preprocess.preprocess_depth
fake_scribble:
  enabled: True
  args:
  - detect_resolution
  ckpt_path: ./models/control_sd15_scribble.pth
  config_path: ./models/cldm_v15.yaml
  detector: annotator.hed.HEDdetector
  postprocess: postprocess.postprocess_fake_scribble
  preprocess: preprocess.preprocess_fake_scribble
hed:
  enabled: True
  args:
  - detect_resolution
  ckpt_path: ./models/control_sd15_hed.pth
  config_path: ./models/cldm_v15.yaml
  detector: annotator.hed.HEDdetector
  postprocess: postprocess.postprocess_hed
  preprocess: preprocess.preprocess_hed
hough:
  enabled: True
  args:
  - value_threshold
  - detect_resolution
  - distance_threshold
  ckpt_path: ./models/control_sd15_mlsd.pth
  config_path: ./models/cldm_v15.yaml
  detector: annotator.mlsd.MLSDdetector
  postprocess: postprocess.postprocess_hough
  preprocess: preprocess.preprocess_hough
normal:
  enabled: True
  args:
  - bg_threshold
  - detect_resolution
  ckpt_path: ./models/control_sd15_normal.pth
  config_path: ./models/cldm_v15.yaml
  detector: annotator.midas.MidasDetector
  postprocess: postprocess.postprocess_normal
  preprocess: preprocess.preprocess_normal
pose:
  enabled: True
  args:
  - detect_resolution
  ckpt_path: ./models/control_sd15_openpose.pth
  config_path: ./models/cldm_v15.yaml
  detector: annotator.openpose.OpenposeDetector
  postprocess: postprocess.postprocess_pose
  preprocess: preprocess.preprocess_pose
scribble:
  enabled: True
  args: []
  ckpt_path: ./models/control_sd15_scribble.pth
  config_path: ./models/cldm_v15.yaml
  detector: ''
  postprocess: postprocess.postprocess_scribble
  preprocess: preprocess.preprocess_scribble
scribble_interactive:
  enabled: False
  args: []
  ckpt_path: ./models/control_sd15_scribble.pth
  config_path: ./models/cldm_v15.yaml
  detector: ''
  postprocess: postprocess.postprocess_scribble
  preprocess: preprocess.preprocess_scribble_interactive
seg:
  enabled: True
  args:
  - detect_resolution
  ckpt_path: ./models/control_sd15_seg.pth
  config_path: ./models/cldm_v15.yaml
  detector: annotator.uniformer.UniformerDetector
  postprocess: postprocess.postprocess_seg
  preprocess: preprocess.preprocess_seg
